export const INFLUENCER_FILTERS = [
    {
        filter:"all",
        image:"https://res.cloudinary.com/dkmnjsvw2/image/upload/v1705654569/cld-sample-4.jpg",
        title:"All",
        number: "20000K Influencers",
    },
    {
        image:"https://res.cloudinary.com/dkmnjsvw2/image/upload/v1705654569/cld-sample-5.jpg",
        filter:"technology",
        title:"Technology",
        number: "200K Influencers",
    },
    {
        image:"https://res.cloudinary.com/dkmnjsvw2/image/upload/v1705654567/cld-sample.jpg",
        filter:"sport",
        title:"Sport",
        number: "200K Influencers",
    },
    {
        image:"https://res.cloudinary.com/dkmnjsvw2/image/upload/v1705654568/cld-sample-2.jpg",
        filter:"fashion",
        title:"Fashion",
        number: "200K Influencers",
    },
    {
        image:"https://res.cloudinary.com/dkmnjsvw2/image/upload/v1721823694/webinar_gonlj3.jpg",
        filter:"food",
        title:"Food",
        number: "200K Influencers",
    },
    {
        image:"https://res.cloudinary.com/dkmnjsvw2/image/upload/v1721823694/webinar_gonlj3.jpg",
        filter:"lifestyle",
        title:"Lifestyle",
        number: "200K Influencers",
    },
    {
        image:"https://res.cloudinary.com/dkmnjsvw2/image/upload/v1721823694/webinar_gonlj3.jpg",
        filter:"beauty",
        title:"Beauty",
        number: "200K Influencers",
    },
    {
        image:"https://res.cloudinary.com/dkmnjsvw2/image/upload/v1721823694/webinar_gonlj3.jpg",
        filter:"fitness",
        title:"Fitness",
        number: "200K Influencers",
    },
    {
        image:"https://res.cloudinary.com/dkmnjsvw2/image/upload/v1721823694/webinar_gonlj3.jpg",
        filter:"gaming",
        title:"Gaming",
        number: "200K Influencers",
    },
    {
        image:"https://res.cloudinary.com/dkmnjsvw2/image/upload/v1721823694/webinar_gonlj3.jpg",
        filter:"tech",
        title:"Tech",
        number: "200K Influencers",
    },
    {
        image:"https://res.cloudinary.com/dkmnjsvw2/image/upload/v1721823694/webinar_gonlj3.jpg",
        filter:"music",
        title:"Music",
        number: "200K Influencers",
    },
    {
        image:"https://res.cloudinary.com/dkmnjsvw2/image/upload/v1721823694/webinar_gonlj3.jpg",
        filter:"parenting",
        title:"Parenting",
        number: "200K Influencers",
    },
    {
        image:"https://res.cloudinary.com/dkmnjsvw2/image/upload/v1721823694/webinar_gonlj3.jpg",
        filter:"health",
        title:"Health",
        number: "200K Influencers",
    },
    {
        image:"https://res.cloudinary.com/dkmnjsvw2/image/upload/v1721823694/webinar_gonlj3.jpg",
        filter:"education",
        title:"Education",
        number: "200K Influencers",
    },
    {
        image:"https://res.cloudinary.com/dkmnjsvw2/image/upload/v1721823694/webinar_gonlj3.jpg",
        filter:"finance",
        title:"Finance",
        number: "200K Influencers",
    },
    {
        image:"https://res.cloudinary.com/dkmnjsvw2/image/upload/v1721823694/webinar_gonlj3.jpg",
        filter:"entertainment",
        title:"Entertainment",
        number: "200K Influencers",
    },
    {
        image:"https://res.cloudinary.com/dkmnjsvw2/image/upload/v1721823694/webinar_gonlj3.jpg",
        filter:"art",
        title:"Art",
        number: "200K Influencers",
    },
    {
        image:"https://res.cloudinary.com/dkmnjsvw2/image/upload/v1721823694/webinar_gonlj3.jpg",
        filter:"photography",
        title:"Photography",
        number: "200K Influencers",
    },
    {
        image:"https://res.cloudinary.com/dkmnjsvw2/image/upload/v1721823694/webinar_gonlj3.jpg",
        filter:"home",
        title:"Home",
        number: "200K Influencers",
    },
    {
        image:"https://res.cloudinary.com/dkmnjsvw2/image/upload/v1721823694/webinar_gonlj3.jpg",
        filter:"automotive",
        title:"Automotive",
        number: "200K Influencers",
    },
    {
        image:"https://res.cloudinary.com/dkmnjsvw2/image/upload/v1721823694/webinar_gonlj3.jpg",
        filter:"business",
        title:"Business",
        number: "200K Influencers",
    },
    {
        image:"https://res.cloudinary.com/dkmnjsvw2/image/upload/v1721823694/webinar_gonlj3.jpg",
        filter:"other",
        title:"Other",
        number: "300K Influencers",
    },
]
